apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: {{ .Chart.Name }}
